# Theory/Computation Problems

### Problem 1 (20 points) 
Show that the stationary point (zero gradient) of the function
$$
\begin{aligned}
    f=2x_{1}^{2} - 4x_1 x_2+ 1.5x^{2}_{2}+ x_2
\end{aligned}
$$
is a saddle (with indefinite Hessian). Find the directions of downslopes away from the saddle. Hint: Use Taylor's expansion at the saddle point. Find directions that reduce $f$.

### Problem 2 (50 points) 

* (10 points) Find the point in the plane $x_1+2x_2+3x_3=1$ in $\mathbb{R}^3$ that is nearest to the point $(-1,0,1)^T$. Is this a convex problem? Hint: Convert the problem into an unconstrained problem using $x_1+2x_2+3x_3=1$.

* (40 points) Implement the gradient descent and Newton's algorithm for solving the problem. Attach your codes along with a short summary including (1) the initial points tested, (2) corresponding solutions, (3) a log-linear convergence plot.

### Problem 3 (10 points) 
Let $f(x)$ and $g(x)$ be two convex functions defined on the convex set $\mathcal{X}$. 
* (5 points) Prove that $af(x)+bg(x)$ is convex for $a>0$ and $b>0$. 
* (5 points) In what conditions will $f(g(x))$ be convex?

### Problem 4 (bonus 10 points)
Show that $f({\bf x}_1) \geq f(\textbf{x}_0) + 
    \textbf{g}_{\textbf{x}_0}^T(\textbf{x}_1-\textbf{x}_0)$ for a convex function $f(\textbf{x}): \mathcal{X} \rightarrow \mathbb{R}$ and for $\textbf{x}_0$, $\textbf{x}_1 \in \mathcal{X}$. 

# Design Problems

### Problem 5 (20 points) 
Consider an illumination problem: There are $n$ lamps and $m$ mirrors fixed to the ground. The target reflection intensity level is $I_t$. The actual reflection intensity level on the $k$th mirror can be computed as $\textbf{a}_k^T \textbf{p}$, where $\textbf{a}_k$ is given by the distances between all lamps to the mirror, and $\textbf{p}:=[p_1,...,p_n]^T$ are the power output of the lamps. The objective is to keep the actual intensity levels as close to the target as possible by tuning the power output $\textbf{p}$.

* (5 points) Formulate this problem as an optimization problem. 
* (5 points) Is your problem convex?
* (5 points) If we require the overall power output of any of the $n$ lamps to be less than $p^*$, will the problem have a unique solution?
* (5 points) If we require no more than half of the lamps to be switched on, will the problem have a unique solution?

# Note

For this homework, you may want to attach sketches as means to explain your ideas. Here is how you can attach images.

![everly1](img/everly7.jpg)

[img](01.jpeg)

[img](02.jpeg)

[img](03.jpeg)

[img](04.jpeg)

[img](05.jpeg)

[img](06.jpeg)

[img](07.jpeg)

In [ ]:
[img]()

In [2]:
# sample code for Problem 2

obj = lambda x: (x - 1)**2  # note that this is 1D. In Prob 2 it should be 2D.
grad = lambda x: 2*(x - 1)  # this is not the correct gradient!
eps = 1e-3  # termination criterion
x0 = 0.  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps
x = soln[k]  # start with the initial guess
error = abs(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
# a = 0.01  # set a fixed step size to start with

# Armijo line search
def line_search(x):
    a = 1.  # initialize step size
    phi = lambda a, x: obj(x) - a*0.8*grad(x)**2  # define phi as a search criterion
    while phi(a,x)<obj(x-a*grad(x)):  # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    a = line_search(x)
    x = x - a*grad(x)
    soln.append(x)
    error = abs(grad(x))
    
soln  # print the search trajectory


[0.0,
 0.25,
 0.4375,
 0.578125,
 0.68359375,
 0.7626953125,
 0.822021484375,
 0.86651611328125,
 0.8998870849609375,
 0.9249153137207031,
 0.9436864852905273,
 0.9577648639678955,
 0.9683236479759216,
 0.9762427359819412,
 0.9821820519864559,
 0.9866365389898419,
 0.9899774042423815,
 0.9924830531817861,
 0.9943622898863396,
 0.9957717174147547,
 0.996828788061066,
 0.9976215910457995,
 0.9982161932843496,
 0.9986621449632622,
 0.9989966087224467,
 0.999247456541835,
 0.9994355924063762,
 0.9995766943047821]

In [33]:
# code without line search
import numpy as np
obj = lambda x: 5*x[0]**2+10*x[1]**2+(12*x[0]*x[1])-8*x[0]-14*x[1]+5# note that this is 1D. In Prob 2 it should be 2D.
def grad(x):
     return (10*x[0]+12*x[1]-8), (20*x[1]+12*x[0]-14)
eps = 1e-3  # termination criterion  
x0= [0.,0.]  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps    
x = soln[k]  # start with the initial guess
error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
a = 0.01  # set a fixed step size to start with

# Armijo line search
#def line_search(x):
 #   a = 1.  # initialize step size
  #  phi = lambda a, x: obj(x) - a*0.8*grad(x)**2  # define phi as a search criterion
   # while phi(a,x)<obj(x-a*grad(x)):  # if f(x+a*d)>phi(a) then backtrack. d is the search direction
    #    a = 0.5*a
    #return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    #a = line_search(x)
    x = x - a*np.array(grad(x))
    soln.append(x)
    error = np.linalg.norm(grad(x))
    
soln  # print the search trajectory

[[0.0, 0.0],
 array([0.08, 0.14]),
 array([0.1352, 0.2424]),
 array([0.172592, 0.317696]),
 array([0.19720928, 0.37344576]),
 array([0.21267486, 0.41509149]),
 array([0.2215964 , 0.44655221]),
 array([0.22585049, 0.4706502 ]),
 array([0.22678742, 0.4894181 ]),
 array([0.2253785 , 0.50431999]),
 array([0.22232225, 0.51641057]),
 array([0.21812076, 0.52644979]),
 array([0.21313471, 0.53498534]),
 array([0.207623  , 0.54241211]),
 array([0.20177124, 0.54901493]),
 array([0.19571233, 0.55499939]),
 array([0.18954117, 0.56051403]),
 array([0.18332537, 0.56566629]),
 array([0.17711288, 0.57053398]),
 array([0.17093751, 0.57517364]),
 array([0.16482292, 0.57962641]),
 array([0.15878546, 0.58392238]),
 array([0.15283623, 0.58808365]),
 array([0.14698257, 0.59212657]),
 array([0.14122912, 0.59606335]),
 array([0.13557861, 0.59990318]),
 array([0.13003237, 0.60365311]),
 array([0.12459076, 0.60731861]),
 array([0.11925345, 0.610904  ]),
 array([0.11401962, 0.61441278]),
 array([0.10888813, 0.617

In [32]:
# code using line search-- gradinet method
import numpy as np
obj = lambda x: 5*x[0]**2+10*x[1]**2+(12*x[0]*x[1])-8*x[0]-14*x[1]+5# note that this is 1D. In Prob 2 it should be 2D.
def grad(x):
     return np.array([10*x[0]+12*x[1]-8, 20*x[1]+12*x[0]-14])
eps = 1e-3  # termination criterion  
x0= [0.,0.]  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps    
x = soln[k]  # start with the initial guess
error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
#a = 0.01  # set a fixed step size to start with


# Armijo line search
def line_search(x):
    a = 1.  # initialize step size
    d=-grad(x)
    phi = lambda a, x: obj(x) + a*0.8*np.dot(grad(x),d)  # define phi as a search criterion
    while phi(a,x)<obj(x-a*grad(x)):  # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    a = line_search(x)
    x = x - a*np.array(grad(x))
    soln.append(x)
    error = np.linalg.norm(grad(x))
    
soln  # print the search trajectory

[[0.0, 0.0],
 array([0.0625  , 0.109375]),
 array([0.10986328, 0.19580078]),
 array([0.14542389, 0.26428223]),
 array([0.17178619, 0.31872964]),
 array([0.19098449, 0.36219818]),
 array([0.20460775, 0.39707492]),
 array([0.21389699, 0.42522498]),
 array([0.2257459 , 0.47098649]),
 array([0.22716314, 0.50022586]),
 array([0.22287655, 0.52006219]),
 array([0.20820431, 0.54894461]),
 array([0.124532  , 0.61427662]),
 array([0.08599204, 0.62803184]),
 array([0.03645422, 0.67896418]),
 array([0.02045071, 0.67844123]),
 array([-0.02277453,  0.70166208]),
 array([-0.03478701,  0.71666537]),
 array([-0.05054416,  0.72192391]),
 array([-0.06039699,  0.73242714]),
 array([-0.08354146,  0.74195478]),
 array([-0.0856678 ,  0.74706109]),
 array([-0.09917469,  0.75791006]),
 array([-0.10562305,  0.7599035 ]),
 array([-0.10953627,  0.76424141]),
 array([-0.11897805,  0.76794228]),
 array([-0.11977577,  0.77009513]),
 array([-0.12519875,  0.77452096]),
 array([-0.12784025,  0.77526882]),
 array([-0.12

In [35]:
# code using line search-- newton method
import numpy as np
obj = lambda x: (2-2*x[0]-3*x[1])**2 + x[0]**2 +(x[1]-1)**2# note that this is 1D. In Prob 2 it should be 2D.
def grad(x):
     return np.array([10*x[0]+12*x[1]-8, 20*x[1]+12*x[0]-14])
eps = 1e-3  # termination criterion  
x0= np.zeros((2),dtype=int)  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps    
x = soln[k]  # start with the initial guess
error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
a = 1  # set a fixed step size to start with

# Armijo line search
def line_search(x):
    a = 1.  # initialize step size
    h=([[10,12],[12,20]])
    d=-np.matmul(np.linalg.inv(h),grad(x))
    def phi(a,x):
        return obj(x)+a*0.8*np.dot(grad(x),d)
    
#     phi = lambda a, x: obj(x) + a*0.8*np.dot(grad(x),d)  # define phi as a search criterion
    while phi(a,x)<obj(x+a*d):  # while phi(a,x)<obj(x-a*grad(x)): # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    a = line_search(x)
    h=([[10,12],[12,20]])
    d=-np.matmul(np.linalg.inv(h),grad(x))
    x = x+a*d
    soln.append(x)
    error = np.linalg.norm(grad(x))
    
soln  # print the search trajectory

[array([0, 0]),
 array([-0.03571429,  0.19642857]),
 array([-0.0625 ,  0.34375]),
 array([-0.08258929,  0.45424107]),
 array([-0.09765625,  0.53710938]),
 array([-0.10895647,  0.5992606 ]),
 array([-0.11743164,  0.64587402]),
 array([-0.12378802,  0.68083409]),
 array([-0.1285553 ,  0.70705414]),
 array([-0.13213076,  0.72671918]),
 array([-0.13481236,  0.74146795]),
 array([-0.13682355,  0.75252954]),
 array([-0.13833195,  0.76082572]),
 array([-0.13946325,  0.76704786]),
 array([-0.14031172,  0.77171447]),
 array([-0.14094808,  0.77521442]),
 array([-0.14142534,  0.77783939]),
 array([-0.14178329,  0.77980811]),
 array([-0.14205176,  0.78128466]),
 array([-0.1422531 ,  0.78239206]),
 array([-0.14240411,  0.78322262]),
 array([-0.14251737,  0.78384554]),
 array([-0.14260231,  0.78431272]),
 array([-0.14266602,  0.78466311]),
 array([-0.1427138 ,  0.78492591]),
 array([-0.14274964,  0.785123  ]),
 array([-0.14277651,  0.78527082]),
 array([-0.14279667,  0.78538169]),
 array([-0.1428117